name: mvvm_templet
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  get: ^4.6.5
  get_it: ^7.2.0
  intl: ^0.17.0
  parse_server_sdk_flutter: ^3.1.3
  provider: ^6.0.3
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/png/
    - assets/images/jpeg/
    - assets/images/svg/
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/GraphikRegular.otf
        - asset: assets/fonts/GraphikBold.otf
          weight: 700
        - asset: assets/fonts/GraphikSemibold.otf
          weight: 600
